# Generated by Django 4.2.2 on 2023-08-05 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("RNO", models.CharField(max_length=122)),
                ("SName", models.CharField(max_length=122)),
                ("Reason", models.TextField()),
            ],
        ),
    ]
