# Generated by Django 4.2.3 on 2023-09-07 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_admin_rno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_id', models.CharField(max_length=10, unique=True)),
                ('Name', models.CharField(max_length=122)),
                ('Year', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RNO', models.CharField(max_length=10)),
                ('SName', models.CharField(max_length=122)),
                ('Reason', models.TextField()),
                ('date_requested', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RNO', models.CharField(max_length=10)),
                ('SName', models.CharField(max_length=122)),
                ('Year', models.PositiveIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
